# This is for the most recent Python 3 version of mkdocs.
# To use it, remove "Py3" from the filename.
# Change these to reflect the user and site details.
site_name: VTKEx
site_url: https://ajpmaclean.github.io/VTKEx/site/
repo_name: ajpmaclean/VTKEx
repo_url: https://github.com/ajpmaclean/VTKEx

theme:
    name: material
    custom_dir: custom_theme/

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.magiclink
  - admonition
  - codehilite:
      guess_lang: true
  - footnotes
  - toc:
        permalink: true
google_analytics:
  -  'UA-3660134-4'
  -  'auto'
extra_css:
  -  'stylesheets/extra.css'
copyright: '<font color=#666>Content is available under </font><a href="https://creativecommons.org/licenses/by/2.5/" title="Attribution2.5">Attribution2.5</a> <font color=#666>unless otherwise noted.</font>'
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
